<a href="https://colab.research.google.com/github/IngerMasha/week11/blob/main/Intro_to_Numpy_day2_Exercises_XP_Gold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array1 = np.random.rand(5, 5)
min_val = np.min(array1)
max_val = np.max(array1)
print(f"Min: {min_val}, Max: {max_val}")


Min: 0.021044739893715803, Max: 0.8655854507847744


In [2]:
matrix2 = np.random.rand(3, 3)
mean2 = np.mean(matrix2)
std2 = np.std(matrix2)
normalized_matrix2 = (matrix2 - mean2) / std2
print(normalized_matrix2)

[[ 0.0773239  -0.18288044 -0.49198789]
 [-0.54537502 -0.99583955  1.83287636]
 [ 0.45131446  1.31575405 -1.46118586]]


In [4]:
array3 = np.linspace(0, 10, 50, endpoint=False)
print(array3)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [3]:
matrix4a = np.random.rand(5, 3)
matrix4b = np.random.rand(3, 2)
result4 = np.dot(matrix4a, matrix4b)
print(result4)

[[0.5060662  1.36803157]
 [0.48531284 0.92359353]
 [0.5162027  1.19864849]
 [0.59757437 1.66670857]
 [0.45772982 0.88130484]]


In [5]:
matrix5a = np.array([[1, 2, 3], [4, 5, 6]])
matrix5b = np.array([[7, 8], [9, 10], [11, 12]])
result5 = np.dot(matrix5a, matrix5b)
print(result5)

[[ 58  64]
 [139 154]]
