<a href="https://colab.research.google.com/github/IngerMasha/week11/blob/main/Intro_to_Numpy_day2_Exercises_XP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
list1 = [3.14, 2.17, 0, 1, 2]
array2 = np.array(list1, dtype=int)
print(array2)

[3 2 0 1 2]


In [7]:
array3 = np.arange(1, 10).reshape(3, 3)
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
array4 = np.random.rand(4, 5)
print(array4)

[[0.81414372 0.29119218 0.75356521 0.54876969 0.22288413]
 [0.55556681 0.76799692 0.9415352  0.63190131 0.34463198]
 [0.47831629 0.68238953 0.18783868 0.58042168 0.27832803]
 [0.7408225  0.18105503 0.50840593 0.63962908 0.20964209]]


In [6]:
array5 = np.array([[10, 11, 12, 13, 14],
                   [20, 21, 22, 23, 24],
                   [30, 31, 32, 33, 34]])
second_row = array5[1]
print(second_row)

[20 21 22 23 24]


In [5]:
array6 = np.arange(10)
reversed_array6 = array6[::-1]
print(reversed_array6)

[9 8 7 6 5 4 3 2 1 0]


In [3]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
array8 = np.arange(10)
sum8 = np.sum(array8)
average8 = np.mean(array8)
print(f"Sum: {sum8}, Average: {average8}")

Sum: 45, Average: 4.5


In [4]:
array9 = np.arange(1, 21).reshape(4, 5)
print(array9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
array10 = np.arange(10)
odd_numbers = array10[array10 % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
