<a href="https://colab.research.google.com/github/IngerMasha/week11/blob/main/Intro_to_Numpy_day2_Exercises_XP_Ninja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

matrix1 = np.random.rand(5, 5)
matrix1[matrix1 == matrix1.max()] = 0
print(matrix1)

[[0.06163449 0.33439658 0.74338194 0.62666237 0.61738858]
 [0.06561828 0.86028103 0.89390357 0.55272828 0.40935306]
 [0.375328   0.68161863 0.60780748 0.6509008  0.94451447]
 [0.84139925 0.6391534  0.55771189 0.86577286 0.93368262]
 [0.63617961 0.71216384 0.14893766 0.94002213 0.        ]]


In [7]:
array2a = np.random.randint(0, 10, 5)
array2b = np.random.randint(0, 10, 5)
common_values = np.intersect1d(array2a, array2b)
print("Array 1:", array2a)
print("Array 2:", array2b)
print("Common values:", common_values)

Array 1: [6 9 5 8 8]
Array 2: [0 4 9 5 5]
Common values: [5 9]


In [4]:
array3 = np.random.rand(10)
ascending_array = np.sort(array3)
descending_array = np.sort(array3)[::-1]
print(f"Ascending: {ascending_array}")
print(f"Descending: {descending_array}")


Ascending: [0.08500564 0.09228921 0.41349558 0.43136259 0.51203926 0.60977539
 0.73844307 0.79938017 0.87202515 0.92244164]
Descending: [0.92244164 0.87202515 0.79938017 0.73844307 0.60977539 0.51203926
 0.43136259 0.41349558 0.09228921 0.08500564]


In [5]:
matrix4 = np.random.rand(4, 4)
rank4 = np.linalg.matrix_rank(matrix4)
print(f"Rank: {rank4}")

Rank: 4


In [6]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
